### ISSUE TITLE
Umbraco 9 (Beta is out)

### ISSUE THREAD

**Issue by creativesuspects** [enkelmedia/Umbraco7-SeoVisualizer#11] opened 2021-09-20 12:53 UTC
Do you have any plans to upgrade this package for Umbraco 9?

**Comment by enkelmedia** [comment] 2021-09-21 10:01
Hi!

Definitely I'm not sure when I can find the time but for sure during the next couple of weeks. 

If you have an urgent need for it I would be happy to accept a PR. If you are up for it, let me know before you start and we can figure out the best way to do it. Otherwise I'll keep you posted here.

// m

**Comment by creativesuspects** [comment] 2021-09-21 10:06
No urgent need. I've been using SeoVisualizer on Umbraco 8 for a while now and I really like it. With the Umbraco 9 release coming up I was just wondering what your plans were for v9. :-)

**Comment by enkelmedia** [comment] 2021-09-21 10:14
Sweet! I'll make sure to update you here when the release is out!

Cheers!

**Comment by enkelmedia** [comment] 2021-09-28 08:15
Just pushed a new version to NuGet: https://www.nuget.org/packages/UmbracoSeoVisualizer/9.0.0-beta1

@creativesuspects Could you give it a try and see if it works for you as well? 

PS: Don't forget to check "inlcude pre-releases" when trying to add the package to your project. https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

Cheers!

**Comment by creativesuspects** [comment] 2021-09-28 08:41
Awesome! I'll be starting a new v9 project next week (currently working on the front-end), so I'll be able to test the beta version then.

**Comment by enkelmedia** [comment] 2021-09-28 09:39
Great! Keep me posted =D

**Comment by olibos** [comment] 2021-10-05 10:41
It's maybe me but when I use the beta package, it doesn't copy automatically the content from package to App_Plugins.
If I copy it manually everything seems working great.
I'll try with a fresh install of Umbraco 9 and keep you posted.

**Comment by enkelmedia** [comment] 2021-10-05 16:29
Hi!

I’ll see if I can reproduce this, it used to work “on my machine” :)

**Comment by olibos** [comment] 2021-10-05 18:11
I think it's just because the target file is not alligned with the packageId and then the clean & copy actions does not run.
I've made a simple change, and now it
![Works On My Machine](https://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)
too 😉

**Comment by enkelmedia** [comment] 2021-10-05 21:50
Big thank you to @olibos for making some nice adjustments today! I just pushed a new release https://www.nuget.org/packages/UmbracoSeoVisualizer/9.0.0-rc1

This should work better, let me know if things look good and I'll make a the 9.0.0-release official =D

**Comment by olibos** [comment] 2021-10-05 21:54
Thank you!

I'll test it probably tomorrow... I'll keep you posted.

**Comment by olibos** [comment] 2021-10-06 20:51
Hello @enkelmedia ,

As promised, it's installed on our latest project based on Umbraco 9 and it works perfectly!

Thank you for your work 👍

**Comment by enkelmedia** [comment] 2021-10-07 13:36
Great news! I'll close this for now.

Edit: Actually, I'll keep it open until the stable release is out.

**Comment by DevGamer616** [comment] 2021-10-16 14:26
Hi @enkelmedia,
Is there a rough date that the stable release for v9 will appear on Nuget?
Thanks.

**Comment by enkelmedia** [comment] 2021-10-16 16:12
@DevGamer616 Not sure but I’ll try to find time during next week. 

Cheers!

**Closed as completed** 2022-06-01 21:35 UTC
